apiVersion: v1
kind: Pod
metadata:
  name: fastapi-ml-resources
  labels:
    app: fastapi-ml-resources
spec:
  containers:
    - image: viktorroy/online_inference:v1
      name: fastapi-ml
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "100Mi"
          cpu: "250m"
        limits:
          memory: "1000Mi"
          cpu: "1000m"