input_data_path: "data/train.csv"
output_model_path: "models/knn_model.pkl"
metric_path: "models/knn_metrics.json"
input_test_path: "data/test.csv"
output_predictions_path: "models/knn_predictions.txt"
downloading_params:
  train_set_url: "https://drive.google.com/file/d/1oGsm_g0qKRduKanE3C1VCML0EM4CS3pm/view?usp=sharing"
  test_set_url:  "https://drive.google.com/file/d/1EsCpRTxWAHr06PdM9rVdHND4mRvrkGo1/view?usp=sharing"
  train_set_path: "data/train.csv"
  test_set_path: "data/test.csv"
splitting_params:
  val_size: 0.2
  random_state: 3
train_params:
  model_type: "KNeighborsClassifier"
  model_params:
    n_neighbors: 22
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  features_to_drop:
    - "thalach"
  target_col: "condition"