input_data_path: "data/heart_cleveland_upload.csv"
output_model_path: "models/model.pkl"
metric_path: "models/metrics.json"
downloading_params:
  url: "https://drive.google.com/file/d/1HhxadPquWB1JBGTV12KNkhhWD0hVnE1p/view?usp=sharing"
  output_filepath: "data/heart_cleveland_upload.csv"
splitting_params:
  val_size: 0.2
  random_state: 3
train_params:
  model_type: "KNeighborsClassifier"
  model_params:
    n_neighbors: 22
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  features_to_drop:
    - "YrSold"
  target_col: "target"